### ISSUE TITLE
Support for vertical scroll in a slide which has content which vertically overflows slide

### ISSUE THREAD

**Issue by raducoravu** [stefan-jung/org.jung.reveal#2]
Some slides may contain more content than can be possible displayed in a single screen.
Ideally we would have a vertical scroll bar when this is the case.

There is already an issue opened for Reveal JS to which I added my vote:
https://github.com/hakimel/reveal.js/issues/822

I'm just adding an issue here to remember about this. Our QA team noticed this when testing the plugin.

**Comment by stefan-jung** [comment]
Great. I thought about this issue as well. Implementing a scroll bar is quite simple. The difficult thing is to fix the dimensions of the section. The dimensions of the section (containing the slide content) depend on your screen size and the used theme. I think we need some kind of dimension calculator to fix the dimensions to fit to the screen size, because we want the content to fit to the screen. So the browser windows should not scroll but only the section.

**Comment by raducoravu** [comment]
Somebody gave me some code like:

```
        section.scrollable {
        overflow-y: auto  !important;
        overflow-x: hidden !important;
        }
```

but from what I tested it seems you need to specify a height for the slide which would make it not very practical.

**Comment by stefan-jung** [comment]
Thanks, I try to fix that next week. We probably need some JS calculating the height of the division.

**Comment by raducoravu** [comment]
By the way, the style section from the reveal.xsl

```
   <style type="text/css">
```

has Javascript comments in it like "/*" and because of this, it seems not to be interpreted by the browser at all. I had to remove the JS comments from it to test the scroll behavior.

**Comment by stefan-jung** [comment]
Vertical scrollbar is already implemented. Plugin now works with the DITA-OT2.x, tested with the flowers example.
